[package]
name = "rsmdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]

[profile.release]
debug = 1

[dependencies]
xml-rs = "0"


[build-dependencies]
cbindgen = "0.20.0"
