[package]
name = "mdf_rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
regex = "1"
itertools = "0.10"
chrono = "0.4"
byteorder = "1.4"
xml-rs = "0.8"