name: Rust-Test-MDF3

on:
  push:
    branches: [ MDF3-Dev ]
  pull_request:
    branches: [ MDF3-Dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
